apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx
  annotations:
    argocd.argoproj.io/image-updater: automatic
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
